server:
  listen-port: <Listen Port e.g. 9595>
  prom-metric-port: <Listen Port for providing Prometheus Metrics>
  truesight:
    tsps-server: "<TSPS Server Name>"
    tsps-port: <TSPS Server Port e.g. 8043>
    tsim-server: "<TSIM Server Name>"
    tsim-port: <TSIM Server Port e.g. 8443
    ts-cell: "<Cell Name>"
    ts-user: "<TS User>"
    ts-user-pw: "<TS User Password>"
    ts-tenant: "<Tenant Name>"
    ts-event-class: "<Eventclass e.g. EVENT or PROMETHEUS>"

