# on:
#  push:
#    tags:
#      - 'v[0-9]+.*'
on: release

name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    # install dependencies
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2 github.com/patrickmn/go-cache github.com/prometheus/client_golang/prometheus go get github.com/prometheus/client_golang/prometheus/promauto go get github.com/prometheus/client_golang/prometheus/promhttp
    #- name: Install all Go dependencies
    #  run: go get github.com/patrickmn/go-cache github.com/prometheus/client_golang/prometheus go get github.com/prometheus/client_golang/prometheus/promauto go get github.com/prometheus/client_golang/prometheus/promhttp
    #- name: Install all Go dependencies
    #  run: go get github.com/prometheus/client_golang/prometheus
    #- name: Install all Go dependencies
    #  run: go get github.com/prometheus/client_golang/prometheus/promauto
    #- name: Install all Go dependencies
    #  run: go get github.com/prometheus/client_golang/prometheus/promhttp
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: linux
        EXTRA_FILES: "README.md config.yml"
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    # install dependencies
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: linux
        EXTRA_FILES: "README.md config.yml"
  release-linux-arm:
    name: release linux/386
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "arm"
        GOOS: linux
        EXTRA_FILES: "README.md config.yml"
  release-linux-arm64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: arm64
        GOOS: linux
        EXTRA_FILES: "README.md config.yml"
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: darwin
        EXTRA_FILES: "README.md config.yml"
  release-windows-386:
    name: release windows/386
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "386"
        GOOS: windows
        EXTRA_FILES: "README.md config.yml"
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@master
    - name: Install all Go dependencies
      run: go get gopkg.in/yaml.v2
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: amd64
        GOOS: windows
        EXTRA_FILES: "README.md config.yml"
